name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Some input test'
        required: true
        default: 'main'

jobs:
  update_release_draft:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Calculate release version
        id: version
        uses: release-drafter/release-drafter@v5
        with:
          commitish: 'hotfix/1.0.2.x'
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
